### ISSUE TITLE
build/zig fails after when using meson's "--prefix" flag

### ISSUE THREAD

**Issue by shlomif** [bcampbell/zig#2]
Hi!

I learned about this game in the debian-games mailing list.

I did:

```
meson setup --prefix ~/apps/temp-zig-game build
meson compile -C build
meson install -C build
build/zig

```

and it failed due to being unable to find "font.png".

I found this workaround:

```
XDG_DATA_DIRS+=":/home/shlomif/apps/temp-zig-game/share"
```

**Comment by bcampbell** [comment]
Doh. Yes - I was stupidly not even passing in the prefix, and just relying on the default `XDG_DATA_DIRS` recommendations.
That commit should fix it...

**Comment by shlomif** [comment]
@bcampbell : thanks! Seems to be working fine now.
